"""Benchmarks generated by official Harbor adapters run on the shared Harbor task format."""
import json

import pytest

from ctxpress import benchmarks
from ctxpress.harness.jobs import plan as eval_plan
from test_model_accounting import rates

NAMES = ["multi-swe-bench", "swe-bench-multilingual"]


def adapter_output(tmp_path, dataset, revision="fixture-v1", manifest=True):
    """The layout harbor/adapters/multi-swe-bench writes: task.toml, instruction, Dockerfile, tests, solution."""
    root = tmp_path / dataset
    task = root / "cli__cli-1234"
    (task / "environment").mkdir(parents=True)
    (task / "tests").mkdir()
    (task / "solution").mkdir()
    (task / "task.toml").write_text('version = "1.0"\n[task]\nname = "cli__cli-1234"\n[agent]\ntimeout_sec = 3600\n'
                                    '[verifier]\ntimeout_sec = 1800\n[environment]\nbuild_timeout_sec = 1800\n', encoding="utf-8")
    (task / "instruction.md").write_text("Fix the issue described below.\n", encoding="utf-8")
    (task / "environment" / "Dockerfile").write_text("FROM mswebench/cli_m_cli:pr-1234\n", encoding="utf-8")
    (task / "tests" / "test.sh").write_text("#!/bin/bash\npython3 /tests/run_tests.py\n", encoding="utf-8")
    (task / "tests" / "run_tests.py").write_text("print('official RUN/TEST/FIX flow')\n", encoding="utf-8")
    (task / "tests" / "config.json").write_text("{}", encoding="utf-8")
    (task / "solution" / "fix.patch").write_text("diff --git a/x b/x\n", encoding="utf-8")
    if manifest:
        (root / "dataset_manifest.json").write_text(json.dumps({"dataset": dataset, "revision": revision}), encoding="utf-8")
    return root


@pytest.mark.parametrize("name", NAMES)
def test_official_adapter_tasks_are_discovered_with_declared_release(tmp_path, name):
    adapter = benchmarks.get(name)
    tasks = adapter.task_instances(adapter_output(tmp_path, name))
    assert [t["id"] for t in tasks] == ["cli__cli-1234"]
    task = tasks[0]
    assert task["evaluation"]["kind"] == "official-harbor-verifier"
    assert task["evaluation"]["dataset"] == dict(name=name, revision="fixture-v1", evidence="local dataset manifest declaration")
    assert not any("solution" in item["path"] for item in task["inputs"])               # the oracle never reaches the agent
    assert adapter.agent_instruction(task).startswith("Fix the issue")


@pytest.mark.parametrize("name", NAMES)
def test_release_must_be_declared_and_cannot_be_relabelled(tmp_path, name):
    adapter = benchmarks.get(name)
    with pytest.raises(ValueError, match="dataset_manifest"):
        adapter.task_instances(adapter_output(tmp_path / "a", name, manifest=False))
    other = adapter_output(tmp_path / "b", name)
    (other / "dataset_manifest.json").write_text(json.dumps({"dataset": "terminal-bench", "revision": "2.0"}), encoding="utf-8")
    with pytest.raises(ValueError, match="release explicitly"):
        adapter.task_instances(other)


@pytest.mark.parametrize("name", NAMES)
def test_plans_compile_through_the_shared_harbor_driver(tmp_path, name):
    root = adapter_output(tmp_path, name)
    binary = tmp_path / "bin"; binary.mkdir(); (binary / "codex").write_bytes(b"synthetic fixture")
    cfg = dict(schema="ctxpress.eval", version=1, benchmark=name, start_mode="task_start", scope="benchmark", model="main",
               tasks=["cli__cli-1234"], backend="codex_docker", methods=[{"class": "HostDefault"}], repeats=1, workers=1,
               prices={"models": {"main": rates()}}, environment={"data": str(root), "bindir": str(binary)})
    plan = eval_plan.compile_plan(cfg)
    assert plan["benchmark"]["name"] == name and plan["run_count"] == 1
    assert plan["jobs"][0]["compact_limit"] is None
    assert any("task resource manifest" in item for item in plan["missing_environment_files"])   # images not yet pinned


def test_catalog_lists_them_outside_the_fixed_protocol():
    rows = {row["name"]: row for row in benchmarks.describe("task_start")}
    for name in NAMES:
        assert rows[name]["family"] == name and name not in benchmarks.FAMILIES
    assert len(benchmarks.FAMILIES) == 8
